### ISSUE TITLE
Erro com o certificado

### ISSUE THREAD

**Issue by sergiokopplin** [hugobessaa/hugobessa#3]
![rsz_screenshot_from_2015-10-13_105439](https://cloud.githubusercontent.com/assets/2743180/10456778/6cc6c682-7199-11e5-83dc-d6c94b295fd9.png)

Um dos posts do meu site tem uma referência a sua url, e tanto o *http* quanto o *https* apresentaram o mesmo erro no **build do travis**.

Não pesquisei a respeito, mas acredito que gostaria de saber.

**Comment by hugobessaa** [comment]
Obrigado @sergiokopplin!

Estranho, mas aqui tudo parece normal. Farei uma pesquisa mais a fundo para verificar se tudo está em ordem.

![captura de tela 2015-10-13 as 11 08 10](https://cloud.githubusercontent.com/assets/4073936/10457038/ce8a374a-719a-11e5-9c32-0f217eb141f2.png)

Você poderia rodar seu build novamente para verificar se o erro persiste?

**Comment by sergiokopplin** [comment]
Acabei de rodar e deu o mesmo erro. :cry: 

Aqui tem a build: https://travis-ci.org/sergiokopplin/kopplin-website/builds/85136564

**Comment by hugobessaa** [comment]
@sergiokopplin, meu CA Root, AddTrust, ainda não é reconhecido em todos os softwares. Eu ainda não sei a exata causa disso, mas alguns browsers/ferramentas desatualizadas ainda não o reconhecem.

Se importa de atualizar suas ferramentas e rodar novamente os testes? Obrigado :+1:

**Comment by sergiokopplin** [comment]
Desculpe a demora.
Eu tive que remover os links. Ficou assim: 

```
@hugobessaa - hugobessa.com.br
```

Posso fechar a issue?

**Comment by hugobessaa** [comment]
Pode sim!

**Comment by sergiokopplin** [comment]
:metal:
